fixtures:
  repositories:
    apache:  "https://github.com/puppetlabs/puppetlabs-apache.git"
    dirtree: "https://github.com/AlexCline/puppet-dirtree.git"
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    mailman: "#{source_dir}"
