fixtures:
  repositories:
    apache:
      repo: "https://github.com/puppetlabs/puppetlabs-apache.git"
      branch: "1.8.x"
    # transitive dependency of puppetlabs-apache (the other is a current stdlib)
    concat:  "https://github.com/ripienaar/puppet-concat.git"
    dirtree: "https://github.com/AlexCline/puppet-dirtree.git"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      branch: "4.6.x"
  symlinks:
    nagios: "#{source_dir}"
