name 'cypherfox-nagios'
version '1.0.1'

author 'Lutz Behnke (see Readme for history)'
license ''
source 'git://github.com/haw-hh-ai-lab/puppet-nagios'
project_page 'git://github.com/haw-hh-ai-lab/puppet-nagios'
summary 'Provide Support for nagios server and targets'
dependency 'puppetlabs/stdlib', '4.3.2'
dependency 'puppetlabs/apache', '1.2.0'
description 'Starting with this version, only Nagios 3 will be supported'
