name 'cypherfox-nagios'
version '0.1.0'

author 'Lutz Behnke (see Readme for history)'
license ''
source 'git://github.com/haw-hh-ai-lab/puppet-nagios'
project_page 'git://github.com/haw-hh-ai-lab/puppet-nagios'
summary 'Provide Support for nagios server and targets'
dependency 'puppetlabs/stdlib', '4.1.0'
dependency 'puppetlabs/apache', '1.0.1'
